import {
  AlertTriangle,
  ArrowRight,
  BarChart,
  Book,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Layout,
  Loader2,
  Moon,
  MoreVertical,
  Pencil,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = typeof LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  layout: Layout,
  book: Book,
  pencil: Pencil,
  calendar: Calendar,
  barChart: BarChart,
  check: Check,
} as const;
